apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
spec:
  volumeClaimTemplates:
  - metadata:
      name: minio-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 20Gi
